//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.25 at 09:11:56 AM GMT-10:00 
//


package org.hackystat.sensor.ant.javancss.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ncss" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="functions" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="classes" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="javadocs" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ncss",
    "functions",
    "classes",
    "javadocs"
})
@XmlRootElement(name = "averages")
public class Averages {

    @XmlElement(required = true)
    protected String ncss;
    @XmlElement(required = true)
    protected String functions;
    @XmlElement(required = true)
    protected String classes;
    @XmlElement(required = true)
    protected String javadocs;

    /**
     * Gets the value of the ncss property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNcss() {
        return ncss;
    }

    /**
     * Sets the value of the ncss property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNcss(String value) {
        this.ncss = value;
    }

    /**
     * Gets the value of the functions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFunctions() {
        return functions;
    }

    /**
     * Sets the value of the functions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFunctions(String value) {
        this.functions = value;
    }

    /**
     * Gets the value of the classes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClasses() {
        return classes;
    }

    /**
     * Sets the value of the classes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClasses(String value) {
        this.classes = value;
    }

    /**
     * Gets the value of the javadocs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJavadocs() {
        return javadocs;
    }

    /**
     * Sets the value of the javadocs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJavadocs(String value) {
        this.javadocs = value;
    }

}
