//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.03.20 at 10:53:57 AM GMT-10:00 
//


package org.hackystat.sensor.ant.jdepend.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="error" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{}Stats" minOccurs="0"/>
 *         &lt;element ref="{}AbstractClasses" minOccurs="0"/>
 *         &lt;element ref="{}ConcreteClasses" minOccurs="0"/>
 *         &lt;element ref="{}DependsUpon" minOccurs="0"/>
 *         &lt;element ref="{}UsedBy" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "error",
    "stats",
    "abstractClasses",
    "concreteClasses",
    "dependsUpon",
    "usedBy"
})
@XmlRootElement(name = "Package")
public class Package {

    protected String error;
    @XmlElement(name = "Stats")
    protected Stats stats;
    @XmlElement(name = "AbstractClasses")
    protected AbstractClasses abstractClasses;
    @XmlElement(name = "ConcreteClasses")
    protected ConcreteClasses concreteClasses;
    @XmlElement(name = "DependsUpon")
    protected DependsUpon dependsUpon;
    @XmlElement(name = "UsedBy")
    protected UsedBy usedBy;
    @XmlAttribute
    protected String name;

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setError(String value) {
        this.error = value;
    }

    /**
     * Gets the value of the stats property.
     * 
     * @return
     *     possible object is
     *     {@link Stats }
     *     
     */
    public Stats getStats() {
        return stats;
    }

    /**
     * Sets the value of the stats property.
     * 
     * @param value
     *     allowed object is
     *     {@link Stats }
     *     
     */
    public void setStats(Stats value) {
        this.stats = value;
    }

    /**
     * Gets the value of the abstractClasses property.
     * 
     * @return
     *     possible object is
     *     {@link AbstractClasses }
     *     
     */
    public AbstractClasses getAbstractClasses() {
        return abstractClasses;
    }

    /**
     * Sets the value of the abstractClasses property.
     * 
     * @param value
     *     allowed object is
     *     {@link AbstractClasses }
     *     
     */
    public void setAbstractClasses(AbstractClasses value) {
        this.abstractClasses = value;
    }

    /**
     * Gets the value of the concreteClasses property.
     * 
     * @return
     *     possible object is
     *     {@link ConcreteClasses }
     *     
     */
    public ConcreteClasses getConcreteClasses() {
        return concreteClasses;
    }

    /**
     * Sets the value of the concreteClasses property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConcreteClasses }
     *     
     */
    public void setConcreteClasses(ConcreteClasses value) {
        this.concreteClasses = value;
    }

    /**
     * Gets the value of the dependsUpon property.
     * 
     * @return
     *     possible object is
     *     {@link DependsUpon }
     *     
     */
    public DependsUpon getDependsUpon() {
        return dependsUpon;
    }

    /**
     * Sets the value of the dependsUpon property.
     * 
     * @param value
     *     allowed object is
     *     {@link DependsUpon }
     *     
     */
    public void setDependsUpon(DependsUpon value) {
        this.dependsUpon = value;
    }

    /**
     * Gets the value of the usedBy property.
     * 
     * @return
     *     possible object is
     *     {@link UsedBy }
     *     
     */
    public UsedBy getUsedBy() {
        return usedBy;
    }

    /**
     * Sets the value of the usedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsedBy }
     *     
     */
    public void setUsedBy(UsedBy value) {
        this.usedBy = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
