//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.03.20 at 10:53:57 AM GMT-10:00 
//


package org.hackystat.sensor.ant.jdepend.jaxb;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TotalClasses" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="ConcreteClasses" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="AbstractClasses" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Ca" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="Ce" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="A" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="I" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="D" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="V" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "totalClasses",
    "concreteClasses",
    "abstractClasses",
    "ca",
    "ce",
    "a",
    "i",
    "d",
    "v"
})
@XmlRootElement(name = "Stats")
public class Stats {

    @XmlElement(name = "TotalClasses", required = true)
    protected BigInteger totalClasses;
    @XmlElement(name = "ConcreteClasses", required = true)
    protected BigInteger concreteClasses;
    @XmlElement(name = "AbstractClasses", required = true)
    protected String abstractClasses;
    @XmlElement(name = "Ca", required = true)
    protected BigInteger ca;
    @XmlElement(name = "Ce", required = true)
    protected BigInteger ce;
    @XmlElement(name = "A")
    protected double a;
    @XmlElement(name = "I")
    protected double i;
    @XmlElement(name = "D")
    protected double d;
    @XmlElement(name = "V")
    protected double v;

    /**
     * Gets the value of the totalClasses property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalClasses() {
        return totalClasses;
    }

    /**
     * Sets the value of the totalClasses property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalClasses(BigInteger value) {
        this.totalClasses = value;
    }

    /**
     * Gets the value of the concreteClasses property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getConcreteClasses() {
        return concreteClasses;
    }

    /**
     * Sets the value of the concreteClasses property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setConcreteClasses(BigInteger value) {
        this.concreteClasses = value;
    }

    /**
     * Gets the value of the abstractClasses property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbstractClasses() {
        return abstractClasses;
    }

    /**
     * Sets the value of the abstractClasses property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbstractClasses(String value) {
        this.abstractClasses = value;
    }

    /**
     * Gets the value of the ca property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCa() {
        return ca;
    }

    /**
     * Sets the value of the ca property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCa(BigInteger value) {
        this.ca = value;
    }

    /**
     * Gets the value of the ce property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCe() {
        return ce;
    }

    /**
     * Sets the value of the ce property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCe(BigInteger value) {
        this.ce = value;
    }

    /**
     * Gets the value of the a property.
     * 
     */
    public double getA() {
        return a;
    }

    /**
     * Sets the value of the a property.
     * 
     */
    public void setA(double value) {
        this.a = value;
    }

    /**
     * Gets the value of the i property.
     * 
     */
    public double getI() {
        return i;
    }

    /**
     * Sets the value of the i property.
     * 
     */
    public void setI(double value) {
        this.i = value;
    }

    /**
     * Gets the value of the d property.
     * 
     */
    public double getD() {
        return d;
    }

    /**
     * Sets the value of the d property.
     * 
     */
    public void setD(double value) {
        this.d = value;
    }

    /**
     * Gets the value of the v property.
     * 
     */
    public double getV() {
        return v;
    }

    /**
     * Sets the value of the v property.
     * 
     */
    public void setV(double value) {
        this.v = value;
    }

}
