//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.25 at 09:11:56 AM GMT-10:00 
//


package org.hackystat.sensor.ant.javancss.resource.jaxb;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ncss" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ccn" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="javadocs" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "ncss",
    "ccn",
    "javadocs"
})
@XmlRootElement(name = "function")
public class Function {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String ncss;
    @XmlElement(required = true)
    protected BigInteger ccn;
    @XmlElement(required = true)
    protected BigInteger javadocs;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the ncss property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNcss() {
        return ncss;
    }

    /**
     * Sets the value of the ncss property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNcss(String value) {
        this.ncss = value;
    }

    /**
     * Gets the value of the ccn property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCcn() {
        return ccn;
    }

    /**
     * Sets the value of the ccn property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCcn(BigInteger value) {
        this.ccn = value;
    }

    /**
     * Gets the value of the javadocs property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getJavadocs() {
        return javadocs;
    }

    /**
     * Sets the value of the javadocs property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setJavadocs(BigInteger value) {
        this.javadocs = value;
    }

}
