//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.25 at 09:11:56 AM GMT-10:00 
//


package org.hackystat.sensor.ant.javancss.resource.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}object" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}averages" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ncss" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "object",
    "averages",
    "ncss"
})
@XmlRootElement(name = "objects")
public class Objects {

    protected List<Object> object;
    protected List<Averages> averages;
    @XmlElement(required = true)
    protected String ncss;

    /**
     * Gets the value of the object property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the object property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObject().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getObject() {
        if (object == null) {
            object = new ArrayList<Object>();
        }
        return this.object;
    }

    /**
     * Gets the value of the averages property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the averages property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAverages().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Averages }
     * 
     * 
     */
    public List<Averages> getAverages() {
        if (averages == null) {
            averages = new ArrayList<Averages>();
        }
        return this.averages;
    }

    /**
     * Gets the value of the ncss property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNcss() {
        return ncss;
    }

    /**
     * Sets the value of the ncss property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNcss(String value) {
        this.ncss = value;
    }

}
