package edu.hawaii.stack;

/**
 * Thrown when an attempt is made to pop an empty
 * stack or check its top element.
 *
 * @author Philip M. Johnson
 */
public class EmptyStackException extends Exception {

  /**
   * The serial version UID, autogenerated by Eclipse.
   */
  private static final long serialVersionUID = 7236818507144587981L;

  /**
   * Indicates an illegal operation on an empty stack was performed.
   *
   * @param errorMessage The message of the exception thrown.
   */
  public EmptyStackException(String errorMessage) {
    super(errorMessage);
  }

  /**
   * Indicates an illegal operation on an empty stack was performed.
   *
   * @param e The exception thrown.
   */
  public EmptyStackException(Exception e) {
    super(e.getMessage());
  }

  /**
   * Indicates an illegal operation on an empty stack was performed.
   *
   * @param message provides more information about the error.
   * @param cause for the chained exception facility
   */
  public EmptyStackException(String message, Throwable cause) {
    super(message, cause);
  }
}
