//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.25 at 09:11:54 AM GMT-10:00 
//


package org.hackystat.sensor.ant.findbugs.resource.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.hackystat.sensor.ant.findbugs.resource.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Jar_QNAME = new QName("", "Jar");
    private final static QName _SrcDir_QNAME = new QName("", "SrcDir");
    private final static QName _ShortMessage_QNAME = new QName("", "ShortMessage");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.hackystat.sensor.ant.findbugs.resource.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Project }
     * 
     */
    public Project createProject() {
        return new Project();
    }

    /**
     * Create an instance of {@link BugCollection }
     * 
     */
    public BugCollection createBugCollection() {
        return new BugCollection();
    }

    /**
     * Create an instance of {@link SourceLine }
     * 
     */
    public SourceLine createSourceLine() {
        return new SourceLine();
    }

    /**
     * Create an instance of {@link Class }
     * 
     */
    public Class createClass() {
        return new Class();
    }

    /**
     * Create an instance of {@link BugInstance }
     * 
     */
    public BugInstance createBugInstance() {
        return new BugInstance();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Jar")
    public JAXBElement<String> createJar(String value) {
        return new JAXBElement<String>(_Jar_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SrcDir")
    public JAXBElement<String> createSrcDir(String value) {
        return new JAXBElement<String>(_SrcDir_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ShortMessage")
    public JAXBElement<String> createShortMessage(String value) {
        return new JAXBElement<String>(_ShortMessage_QNAME, String.class, null, value);
    }

}
